# Generated by Django 4.0.8 on 2024-06-14 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import urls.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=255, validators=[urls.models.is_https])),
                ('token', models.CharField(blank=True, max_length=255)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('query_params', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UrlUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_users', to='urls.url')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
