# Generated by Django 4.0.8 on 2024-06-17 15:59

import django.contrib.postgres.indexes
from django.db import migrations, models
import urls.models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='query_params',
        ),
        migrations.AlterField(
            model_name='url',
            name='expiration_date',
            field=models.DateTimeField(default=urls.models.get_default_expiration_date),
        ),
        migrations.AlterField(
            model_name='url',
            name='token',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True, validators=[urls.models.is_https]),
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(condition=models.Q(('url', 'https://shayestehhs.com')), fields=['url'], name='ready_to_set_token_urls'),
        ),
        migrations.AddIndex(
            model_name='url',
            index=django.contrib.postgres.indexes.HashIndex(fields=['token'], name='urls_url_token_44aa35_hash'),
        ),
    ]
