# Generated by Django 4.0.8 on 2024-06-21 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0002_remove_url_query_params_alter_url_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='token',
            field=models.CharField(editable=False, max_length=5),
        ),
        migrations.CreateModel(
            name='UrlUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='urls.url')),
            ],
        ),
    ]
