# Generated by Django 5.0.8 on 2024-09-30 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0002_alter_url_token_alter_url_url_urlclick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urluser',
            name='url',
        ),
        migrations.RemoveField(
            model_name='urluser',
            name='user',
        ),
        migrations.DeleteModel(
            name='UrlUsage',
        ),
        migrations.DeleteModel(
            name='UrlUser',
        ),
    ]
